src/Entity/Article.php
<?php

namespace App\Entity;

use ORM\EntityListeners;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\Collection;
use App\Event\EntityListener\ArticleListener;
use DateTime;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
#[ORM\EntityListeners([ArticleListener::class])]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(options: ["default" => true])]
    private ?bool $isPublished = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?User $CreatedBy = null;

    #[ORM\OneToMany(mappedBy: 'article', targetEntity: Commentaire::class, cascade: ['persist', 'remove'])]
    private Collection $commentaire;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'article')]
    private Collection $tags;

    public function __construct()
    {
        $this->commentaire = new ArrayCollection();
        $this->createdAt = new DateTimeImmutable();
        $this->updatedAt = new DateTimeImmutable();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function isIsPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setIsPublished(bool $isPublished): self
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->CreatedBy;
    }

    public function setCreatedBy(?User $CreatedBy): self
    {
        $this->CreatedBy = $CreatedBy;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaire(): Collection
    {
        return $this->commentaire;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaire->contains($commentaire)) {
            $this->commentaire->add($commentaire);
            $commentaire->setArticle($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaire->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getArticle() === $this) {
                $commentaire->setArticle(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
            $tag->addArticle($this);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->removeElement($tag)) {
            $tag->removeArticle($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->title;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Article;
use App\Entity\Tag;
use App\Repository\TagRepository;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Component\Form\AbstractType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('content', CKEditorType::class, [
                'config_name' => 'my_config_1'
            ])
            ->add('isPublished')
            ->add('tags', EntityType::class, [
                'multiple'  => true,
                'attr' => [
                    'class' => "select2"
                ],
                'class' => Tag::class,
                'required' => false
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Entity\Commentaire;
use App\Entity\Tag;
use App\Form\CommentaireType;
use App\Security\Voter\ArticleVoter;
use App\Repository\ArticleRepository;
use App\Security\Voter\CommentaireVoter;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/article')]
class ArticleController extends AbstractController
{
    #[Route('/', name: 'app_article_index', methods: ['GET'])]
    public function index(ArticleRepository $articleRepository): Response
    {
        $this->denyAccessUnlessGranted('POST_VIEW_CRUD', new Article());
        return $this->render('article/index.html.twig', [
            'articles' => $articleRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_article_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ArticleRepository $articleRepository): Response
    {
        $article = new Article();
        $this->denyAccessUnlessGranted('POST_NEW', $article);
        $article->setCreatedBy($this->getUser());
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $articleRepository->save($article, true);

            return $this->redirectToRoute('app_article_show', ['slug' => $article->getSlug()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('article/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{slug}', name: 'app_article_show', methods: ['GET'])]
    public function show(Article $article, Request $request, ArticleRepository $articleRepository): Response
    {
        // $commentaire = new Commentaire();
        // $this->denyAccessUnlessGranted(CommentaireVoter::NEW, $commentaire, 'dddddd');
        // $commentaire->setUser($this->getUser());
        // $form = $this->createForm(CommentaireType::class, $commentaire);
        // $article->addCommentaire($commentaire);
        // $form->handleRequest($request);


        // if ($form->isSubmitted() && $form->isValid()) {
        //     $articleRepository->save($article, true);

        //     return $this->redirectToRoute('app_article_show', ['slug' => $article->getSlug()], Response::HTTP_SEE_OTHER);
        // }

        foreach ($article->getTags() as $key => $value) {
            # code...
            dump($value);
        }

        $this->denyAccessUnlessGranted(ArticleVoter::VIEW, $article, 'article');
        return $this->render('article/show.html.twig', [
            'article' => $article,
            // 'form' => $form->createView(),
        ]);
    }

    #[Route('/{slug}/edit', name: 'app_article_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Article $article, ArticleRepository $articleRepository, EntityManagerInterface $emi): Response
    {

        // foreach ($article->getTags() as $key => $value) {
        //     # code...
        //     dump($value);
        // }

        $this->denyAccessUnlessGranted('POST_EDIT', $article);
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // dd($request);
            $articleRepository->save($article, true);
            // dd($article);

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('article/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{slug}', name: 'app_article_delete', methods: ['POST'])]
    public function delete(Request $request, Article $article, ArticleRepository $articleRepository): Response
    {
        $this->denyAccessUnlessGranted('POST_DELETE', $article);
        if ($this->isCsrfTokenValid('delete' . $article->getSlug(), $request->request->get('_token'))) {
            $articleRepository->remove($article, true);
        }

        return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('app_article_delete', {'slug': article.slug}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.slug) }}">
	<button class="button-delet">Supprimer</button>
</form>

templates/article/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="button-edit">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/article/_navbar.html.twig
{% if article.CreatedBy == app.user or is_granted('ROLE_MODERATOR') %}
	<nav class="navbar-second">
		<div class="navbar-block"></div>
		<div class="navbar-block">
			<div class="navbar-item">
				<a href="{{ path('app_article_edit', {'slug': article.slug}) }}" class="button-edit">Editer</a>
				{% if article.CreatedBy == app.user or is_granted('ROLE_ADMIN') %}
					{{ include('article/_delete_form.html.twig') }}
				{% endif %}
			</div>
		</div>
	</nav>
{% endif %}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}
    <h1>Edit Article</h1>

    {{ include('article/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_article_index') }}">back to list</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index
{% endblock %}

{% block body %}
	<h1>Article index</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Title</th>
				{# <th>Content</th> #}
				<th>Creator</th>
				<th>Published</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			<pre>
			
		</pre>
			{# {{ dump(articles) }} #}
			{% for article in articles %}
				<tr style="{% if article.isPublished == 0 %} background-color:#bbbbbb;{% endif %}">
					<td>{{ article.id }}</td>
					<td>{{ article.title }}</td>
					{# <td>{{ article.content }}</td> #}
					<td>
						{% if article.CreatedBy.id is defined %}
							{{ article.createdBy.email }}
						{% else %}
							NULL
						{% endif %}
					</td>

					<td>
						{% if article.isPublished == 1 %}
							True
							{%else%}
							False
						{% endif %}
					</td>
					<td>
						<a href="{{ path('app_article_show', {'slug': article.slug}) }}">show</a>
						{% if is_granted('ROLE_EDITOR') %}
							<a href="{{ path('app_article_edit', {'slug': article.slug}) }}">edit</a>
						{% endif %}

					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="5">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('app_article_new') }}">Create new</a>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}
    <h1>Create new Article</h1>

    {{ include('article/_form.html.twig') }}

    <a href="{{ path('app_article_index') }}">back to list</a>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
	{{ parent() }}
	{{ encore_entry_script_tags('article') }}
{% endblock %}

{% block title %}Article
{% endblock %}

{% block body %}
	{% include "article/_navbar.html.twig" %}
	<div class="show-article">
		<div class="article-title">
			<h2>{{ article.title }}</h2>
		</div>
		<div class="article-authors">
			{% if  article.createdAt !=  null %}
				Publié le
				{{ article.createdAt | date('d-m-Y') }}
				par
				{{ article.CreatedBy.email}}
			{% elseif article.updatedAt !=  null %}
				Mis à jour le
				{{ article.updatedAt | date('d-m-Y') }}
				par
				{{ article.CreatedBy.email}}
			{% endif %}
		</div>
		<div class="article-content">
			{{ article.content | raw }}
		</div>

		<p class="chip-container">
			{% for tag in article.tags %}
				<a href="{{ path("app_tag_show", {'id': tag.id}) }}" class="chip">{{ tag.name }}</a>
			{% endfor %}
		</p>
	</div>


	<div class="show-commentaire">

		<div class="commentaire-title">
			Commentaires
		</div>

		<div class="commentaire-action">
			{% if is_granted('ROLE_SIMPLE_USER') %}
				<a href="{{ path('app_commentaire_add', {'id': article.id}) }}" class="button-read">Ajouter un commentaire</a>
				<a id="add_commentaire_button" href="#">Click me</a>
				<div>
					{# {% include "article/_form.html.twig" %} #}
				</div>
			{% else %}
				<a href="{{ path('app_commentaire_add', {'id': article.id}) }}">Connectez vous pour commenter cet article.</a>

			{% endif %}
		</div>

		{% for commentaire in article.commentaire %}
			<div class="commentaire-item" id="{{ commentaire.id }}">
				<img src="https://via.placeholder.com/150" alt="" class="commentaire-author-pp">
				<div class="commentaire-content">
					<div class="commentaire-author-name">
						{{ commentaire.user.email }}
					</div>
					<div class="commentaire-text">
						{{commentaire.content | raw}}
					</div>
					<div class="commentaire-date">
						Le
						{{commentaire.createdAt | date('d-m-Y')}}
					</div>
				</div>
			</div>

		{% endfor %}
	</div>
{% endblock %}